### ISSUE TITLE
Command line mode with XML output

### ISSUE THREAD

**Issue by MichaelKetting** [telerik/JustAssembly#16]
In relation to https://github.com/telerik/JustAssembly/issues/14 it would be great to offer a general purpose command line option for the tool, to be used with CI systems, etc. The result could be an XML . This XML could then be piped into various tools, e.g. check that two builds are identical, get semver-differences in the API, etc.

**Comment by tsviatko** [comment]
The ToXml method of the [IDiffItem](https://github.com/telerik/JustAssembly/blob/7c06943f8063a1ff1c2928eb1eea971144de1691/Core/JustAssembly.Core/IDiffItem.cs) interface will be a really good place to start implementing that.

**Comment by MichaelKetting** [comment]
Thanks.

**Comment by tsviatko** [comment]
Sorry about the terse reply. As mentioned in [#14](https://github.com/telerik/JustAssembly/issues/14) we are really limited on resources right now. I found some free time and made the most of it by providing just the useful info.

**Comment by adimitrov93** [comment]
Closed by #24
