### ISSUE TITLE
Accept file names on the command line of JustAssembly.exe to bypass the opening dialog.

### ISSUE THREAD

**Issue by colin-luke** [telerik/JustAssembly#27]
We use Surround for source control. It has the ability to do comparisons between versions of binary files. It allows you to configure the tool used to do the comparison. I would like to be able to configure it such that SCM can supply the names of files it creates as command line params. Something like this: "C:\Program Files (x86)\Telerik\JustAssembly\Libraries\JustAssembly.exe" "%1" "%2"

**Comment by tsviatko** [comment]
You are not the first one to request such a feature *(#16) so we have implemented it already. Please, check out http://www.telerik.com/blogs/integrate-assembly-diff-in-your-build-using-justassembly

**Comment by colin-luke** [comment]
This is not the same thing at all. What I'm asking for is the ability to pass file names to JustAssembly.exe such that I can visually inspect 2 different assemblies. Right now if Surround ties to bring up JustAssembly it still gives me the opening dialog to select the assemblies myself. What I want is a mechanism to pass files names to JustAssembly, not JustAssembly.CommandLineTool.exe, so that it immediately loads both files to perform a visual comparison.

**Comment by tsviatko** [comment]
Ah I see now. Yeah that is not there. It should be easy to implement though.

**Comment by colin-luke** [comment]
Excellent! That's good to hear. Glad to know it won't be difficult. I assumed it wouldn't be. Would be of great use. Looking forward to using that feature one day.

**Comment by jozamp** [comment]
Ran into this today, myself. Would be super useful to be able to pass filenames on the command line for the GUI. Any word on when / if this might be implemented? Thanks!

**Comment by tsviatko** [comment]
This feature is not on our current release plan. That's why we marked it as "Help wanted" so that the community could consider implementing it while being certain there will not be duplicate effort.

**Comment by jozamp** [comment]
Ah, I see. Well, I'll take a look, then. :)

**Comment by colin-luke** [comment]
I actually started to implement this myself. Not a complete solution. Only took me about an hour to add just enough code to inspect the command line arguments to use and the assemblies to compare. I’d be willing to share it.

Sent from my iPhone

On Mar 20, 2018, at 7:49 PM, Josh Zampino <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, I see. Well, I'll take a look, then. :)

**Comment by SugoiDev** [comment]
@colin-luke If you can share your solution, I would be interested in taking a look!
Are you checking for 3 arguments as not to interfere with the current functionality of exporting to xml?

**Comment by colin-luke** [comment]
Actually I'm only only checking for 2. My solution is very rudimentary (i.e. "quick and dirty").  I'm just looking at the first 2 arguments passed to the OnStartup of App.xaml.cs and passing those args on to JustAssemblyBootstraper and so on. Then it gets passed on to NewSessionViewModel and then creates a NewSessionDialog and goes from there. I just needed a way to point or source control client to JA with 2 file names. I assume the first arg is the "old file" and the second arg is the "new file". There's a lot that could go wrong with this. For instance what if one arg is a file and the other is a directory? There's a lot more that could be done with this. Regrefully, I did not perform a proper "git clone" of the repo, just downloaded zip files and had at it. Ergo, I'm attaching the files I modified so you can see what I did and perhaps make a proper pull request. I tried to include only the files I changed back in August. Let me know if I'm missing something.
[JustAssembly_WithArgs.zip](https://github.com/telerik/JustAssembly/files/1869111/JustAssembly_WithArgs.zip)

**Comment by SugoiDev** [comment]
Alright, thanks!

I read your changes and ran a diff against this repo, and it seems good.
When I have a bit of time I'll flesh out this feature and add some tests to submit a PR.

But first I need to confirm: @tsviatko are you guys willing to review/accept a PR for this feature?

**Comment by tsviatko** [comment]
@SugoiDev  yes, most definitely. That's why we marked it as "Help wanted". Your PR would be most welcome.

**Comment by sherland** [comment]
Any progress on this?

**Comment by adimitrov93** [comment]
Aside from what's in this issue, there is no progress on this (as far as we know).

**Comment by SugoiDev** [comment]
Hey @sherland, I'm going to submit a PR in a little while.

Turns out @colin-luke "rudimentary" solution was already pretty nice and simple (thanks!)
I've added a few extra checks and an error message window when the arguments are invalid and I'm forking to push right now.

**Comment by ericnewton76** [comment]
So any word on this?

**Comment by adimitrov93** [comment]
@ericnewton76 We had some technical difficulties, which are now resolved. I hope the PR will be merged soon.

**Comment by adimitrov93** [comment]
Huge thanks to @SugoiDev and @colin-luke for the help on this feature!
