### ISSUE TITLE
Installer broken

### ISSUE THREAD

**Issue by JVimes** [telerik/JustAssembly#29]
I went to http://www.telerik.com/justassembly, clicked the Download button, and ran the installer: `JustAssembly_2017_2_713_1_Free.exe`.

It gave me a "old installer version" error:

![image](https://user-images.githubusercontent.com/6148201/29438278-d723c38a-8372-11e7-9c17-d3b3d2d2c491.png)

That link for the new version downloads the same version.

**Comment by stephen-edginton** [comment]
Had the same issue please fix this tool looks great.

**Comment by tsviatko** [comment]
Should be fixed now.

**Comment by JVimes** [comment]
Fixed for me. Thanks!
