### ISSUE TITLE
[bug]Application Error

### ISSUE THREAD

**Issue by pedoc** [telerik/JustAssembly#30]
error detail:

错误应用程序名称: JustAssembly.exe，版本: 2017.2.713.1，时间戳: 0x59673112
错误模块名称: KERNELBASE.dll，版本: 10.0.15063.502，时间戳: 0x005405b5
异常代码: 0xe0434352
错误偏移量: 0x0000000000069e08
错误进程 ID: 0xca8
错误应用程序启动时间: 0x01d31cd5d7c4ffae
错误应用程序路径: C:\Program Files (x86)\Telerik\JustAssembly\Libraries\JustAssembly.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: f5a68108-6b31-4717-86d9-1fbaff1b495c
错误程序包全名: 
错误程序包相对应用程序 ID: 

应用程序: JustAssembly.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.ArgumentOutOfRangeException
   在 Dragablz.DragablzColors.BlendColor(System.Windows.Media.Color, System.Windows.Media.Color, Double)
   在 Dragablz.DragablzColors.GetBalancedWindowGlassBrush()
   在 Dragablz.DragablzColors..cctor()

异常信息: System.TypeInitializationException

异常信息: System.Reflection.TargetInvocationException
   在 System.RuntimeFieldHandle.GetValue(System.Reflection.RtFieldInfo, System.Object, System.RuntimeType, System.RuntimeType, Boolean ByRef)
   在 System.Reflection.RtFieldInfo.UnsafeGetValue(System.Object)
   在 System.Reflection.RtFieldInfo.GetValue(System.Object)
   在 System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(System.Type, System.String, System.Object ByRef)
   在 System.Windows.Markup.StaticExtension.ProvideValue(System.IServiceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

异常信息: System.Windows.Markup.XamlParseException
   在 System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   在 System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter)
   在 System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter)
   在 System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector, System.Collections.Generic.List`1<System.Windows.DependencyObject>, System.Windows.UncommonField`1<System.Collections.Hashtable>)
   在 System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject, System.Collections.Generic.List`1<System.Windows.DependencyObject>)
   在 System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate)
   在 System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.FrameworkElement)
   在 System.Windows.FrameworkElement.ApplyTemplate()
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Grid.MeasureCell(Int32, Boolean)
   在 System.Windows.Controls.Grid.MeasureCellsGroup(Int32, System.Windows.Size, Boolean, Boolean, Boolean ByRef)
   在 System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Decorator.MeasureOverride(System.Windows.Size)
   在 System.Windows.Documents.AdornerDecorator.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Window.MeasureOverrideHelper(System.Windows.Size)
   在 System.Windows.Window.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Interop.HwndSource.SetLayoutSize()
   在 System.Windows.Interop.HwndSource.set_RootVisualInternal(System.Windows.Media.Visual)
   在 System.Windows.Window.SetRootVisual()
   在 System.Windows.Window.SetRootVisualAndUpdateSTC()
   在 System.Windows.Window.SetupInitialState(Double, Double, Double, Double)
   在 System.Windows.Window.CreateSourceWindow(Boolean)
   在 System.Windows.Window.ShowHelper(System.Object)
   在 Microsoft.Practices.Prism.MefExtensions.MefBootstrapper.Run(Boolean)
   在 JustAssembly.App.OnStartup(System.Windows.StartupEventArgs)
   在 System.Windows.Application.<.ctor>b__1_0(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 JustAssembly.App.Main()

**Comment by pedoc** [comment]
The first installation, running normally.then I installed it Visual Studio 2010，there was a mistake

**Comment by pedoc** [comment]
fixed,see #31

**Comment by tibel** [comment]
This affects all systems where the culture is not en-US (e.g. German).

**Comment by adimitrov93** [comment]
Hi @tibel. Would it be possible to share some more details for your system - OS, .NET Framework version etc.? I've tried to reproduce the problem on a Windows 10 with German culture but without luck. Also, what do you do to make it happen? A step-by-step guide would be great.

**Comment by tibel** [comment]
OS: Windows 10 Enterpreise 2016 LTSB
.NET Framework: 4.6.2
Language: English (United States)
Format: German (Austria)


JustAssembly R2 2017 SP2 (17.2.713.0)

Inner Exception:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: percentage
   at Dragablz.DragablzColors.BlendColor(Color color1, Color color2, Double percentage)
   at Dragablz.DragablzColors.GetBalancedWindowGlassBrush()
   at Dragablz.DragablzColors..cctor()
```

[exception.txt](https://github.com/telerik/JustAssembly/files/1766668/exception.txt)

**Comment by adimitrov93** [comment]
Hi, @tibel. Thanks for the follow-up.

Tried with your culture settings but without luck. Then I checked the issue you have linked and it lead me to the actual issue, which is https://github.com/ButchersBoy/Dragablz/issues/88 and as it seems - it has been already fixed, so update of Dragablz to latest version should do the trick. FWIW it seems to be a bug, which can be reproduced in certain Windows 10 versions, rather than a culture-related problem.

I've already updated Dragablz to the latest version, but without a reproduction scenario I'm unable to test the fix. Are you willing to try an internal build with the applied fix?

**Comment by tibel** [comment]
@adimitrov93 Sure. I can test it on my machine. Where can I get the internal build?

**Comment by adimitrov93** [comment]
@tibel Here you are.

[JustAssembly_InternalBuild.zip](https://github.com/telerik/JustAssembly/files/1785127/JustAssembly_InternalBuild.zip)

**Comment by tibel** [comment]
@adimitrov93 Tested on two machines. Your changes fixed the issue. :thumbsup:

**Comment by adimitrov93** [comment]
@tibel Great. Thank you for taking the time to help us our on this one. This fix is going to be shipped in the next release of JustAssembly.
