### ISSUE TITLE
In command-line diff in body of methods no save in xml file

### ISSUE THREAD

**Issue by mpx1368** [telerik/JustAssembly#32]
in command line when i set a optional parameter on method no save in xml file but in UI show on list
dll file for test is attached

[2.zip](https://github.com/telerik/JustAssembly/files/1260150/2.zip)

**Comment by adimitrov93** [comment]
What is the exact command you enter in the command line? Keep in mind that in order to use the command-line feature of JustAssembly you should use `JustAssembly.CommandLineTool.exe`, instead of `JustAssembly.exe`.

**Comment by mpx1368** [comment]
please test with file in 2.zip attached in first post in command line and UI in command line mode xml file is empty but in ui mode show modify method screenshot attached
![justassm](https://user-images.githubusercontent.com/31440517/29826119-afdec98c-8ceb-11e7-9e7c-fa3b304d0cf5.jpg)

**Comment by yeganehaym** [comment]
+1
yes 
when i working with command tool
the xml file is empty

**Comment by adimitrov93** [comment]
Ah, now I understand you. This isn't a bug, but more like a feature. The command-line tool compares only the public API. In your case the change does not affect the public API and that's why the xml file is empty. If you change the access modifier of the method for example, then the xml will contain description of the change.

**Comment by mpx1368** [comment]
i can't understand please help me with sample

**Comment by adimitrov93** [comment]
Sure, here you are.
[JustAssembly.Sample.zip](https://github.com/telerik/JustAssembly/files/1269690/JustAssembly.Sample.zip)

**Comment by mpx1368** [comment]
i have no source change modifier to private and i want change in body of method in commandline
