### ISSUE TITLE
CommandLine application gives no output

### ISSUE THREAD

**Issue by tno2007** [telerik/JustAssembly#55]
When I'm using JustAssembly.CommandLineTool.exe , I get a file with 0 kB size. 

Here is an example of what I type and the output:

`C:\Program Files (x86)\Progress\JustAssembly\Libraries>JustAssembly.CommandLineTool.exe "C:\temp\old\FC.NamingServices.dll" "c:\temp\new\FC.NamingServices.dll" "c:\temp\output.xml" `

`API differences calculated successfully.`

output.xml is created, however when I check the xml file, there is no output, just a empty file.

**Comment by adimitrov93** [comment]
Are there any differences between the assemblies? Keep in mind that the command-line interface calculates only public API differences.

**Comment by adimitrov93** [comment]
Would it be possible to provide those assemblies for reproduction purposes?

**Comment by tno2007** [comment]
I cannot share the assemblies in the original question as I'll get into trouble at our company, but attached is an assembly I just created and tested with. Both old and new versions is in the zip file.

[ClassLibrary1.zip](https://github.com/telerik/JustAssembly/files/2643765/ClassLibrary1.zip)

**Comment by adimitrov93** [comment]
The command-line interface of JustAssembly calculates only **public API differences**. That's why the attached assemblies produce empty file. The difference between the 2 assemblies is the addition of 2 private methods.

If you want such feature feel free to open new issue describing the use case you need.
